# config.yml
# validate with pydantic
metadata:
  version: 1.0
  environment: "dev"

data_generator:
  enabled: True
  start_date: "2023-01-01"
  end_date: "2023-02-01"
  anchor_prices:
    GME: 150.0
    BYND: 200.0
    BP: 15.0

data_processor:
  handle_missing_values:
    enabled: True
    strategy: "drop"  # options: drop, forward_fill
  make_stationary:
    enabled: True
    method: "difference"  # options: difference, log
  test_stationarity:
    method: "ADF"
    p_value_threshold: 0.05  # Significance level: p-value below this means the series is stationary
  scaling:
    method: "standardize"  # options: standardize, minmax

stats_model:
  ARIMA:
    enabled: False
    parameters_fit:
      p: 2
      d: 1
      q: 4
    parameters_predict_steps: 3
  GARCH:
    enabled: True
    parameters_fit:
      p: 1
      q: 1
      dist: "t"  # options: normal, t
    parameters_predict_steps: 3

